baseURL = "https://marek.omasta.net"
title = "Marek Omasta"
theme = ["blank"]
enableRobotsTXT = true
loadJQuery = false
timeout = "180s"
summaryLength = 18

# Disable Categories and Tags pages
disableKinds = ['taxonomy', 'term']

[minify]
  minifyOutput = true
  [minify.tdewolff]
    [minify.tdewolff.html]
      keepWhitespace = false
    [minify.tdewolff.xml]
      keepWhitespace = false
      
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

defaultContentLanguage = 'en'

[languages]
  [languages.cs]
    contentDir = 'content/cs'
    languageName = 'Čeština'
    languageCode = "cs"
    weight = 2
      [languages.cs.params]
          images = ['images/profile-picture-og-2.jpg']
          description = "Moje osobní stránka, archiv memes, odkazy na moje profily a obsah online"
    [languages.cs.menu]
    [[languages.cs.menu.main]]
      name = 'Domů'
      url = '/cs/'
      weight = 0
    [[languages.cs.menu.main]]
      name = 'Memes'
      url = '/cs/memes'
      weight = 0
  [languages.en]
    contentDir = 'content/en'
    languageName = 'English'
    languageCode = "en-gb"
    weight = 1
    [languages.en.params]
      images = ['images/profile-picture-og-2.jpg']
      description = "My personal website, meme archive, links to my profiles and my online content"
    [languages.en.menu]
    [[languages.en.menu.main]]
      name = 'Home'
      url = '/'
      weight = 0
    [[languages.en.menu.main]]
      name = 'Memes'
      url = '/memes'
      weight = 0
