baseURL = "https://marek.omasta.net"
title = "Marek Omasta"
theme = ["blank"]
enableRobotsTXT = true
loadJQuery = false
timeout = "180s"
summaryLength = 18
removePathAccents = true
defaultContentLanguage = 'en'
titleCaseStyle = 'none'

[minify]
  minifyOutput = true
  [minify.tdewolff]
    [minify.tdewolff.html]
      keepComments = false
    KeepSpecialComments = true
    keepWhitespace = false
    [minify.tdewolff.xml]
      keepWhitespace = false
      
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  tag = "tags"

[outputs]
  home = ['html']
  section = ['html']
  taxonomy = ['html']
  term = ['html']
    
[languages]
  [languages.en]
    contentDir = 'content/en'
    languageName = 'English'
    languageCode = "en-GB"
    weight = 1
    [languages.en.params]
      dateFormat = "2 Jan 2006"
      images = ['images/profile-picture-og-2.jpg']
      description = "Personal website of Marek Omasta, meme archive, links to my profiles and my content online"
    [languages.en.menu]
    [[languages.en.menu.main]]
      name = 'Home'
      pageref = '/'
      weight = 0
    [[languages.en.menu.main]]
      name = 'Memes'
      pageref = '/memes'
      weight = 0

  [languages.cs]
    contentDir = 'content/cs'
    languageName = 'Čeština'
    languageCode = "cs-CZ"
    weight = 2
      [languages.cs.params]
          dateFormat = "2. 1. 2006"
          images = ['images/profile-picture-og-2.jpg']
          description = "Osobní stránka Marka Omasty, archiv memes, odkazy na moje profily a obsah online"
    [languages.cs.menu]
    [[languages.cs.menu.main]]
      name = 'Domů'
      pageref = '/'
      weight = 0
    [[languages.cs.menu.main]]
      name = 'Memes'
      pageref = '/memes'
      weight = 0