baseURL = "https://marek.omasta.net"
title = "Marek Omasta"
theme = ["blank"]
enableRobotsTXT = true
loadJQuery = false
timeout = "180s"
summaryLength = 18
enableEmoji=true

[minify]
  minifyOutput = true
  [minify.tdewolff]
  	[minify.tdewolff.html]
	  	keepWhitespace = false
    [minify.tdewolff.xml]
      keepWhitespace = false

defaultContentLanguage = 'en'

[languages]
  [languages.cs]
    contentDir = 'content/cz'
    languageName = 'Čeština'
    languageCode = "cs"
    description = "Moje osobní stránka, archiv memes, odkazy na moje profily a obsah online"
    weight = 2
    [languages.cs.menu]
    [[languages.cs.menu.main]]
      name = 'Domů'
      url = '/cs/'
      weight = 0
    [[languages.cs.menu.main]]
      name = 'Memes'
      url = '/memes'
      weight = 0
  [languages.en]
    contentDir = 'content/en'
    languageName = 'English'
    languageCode = "en-gb"
	description = "My personal website, meme archive, links to my profiles and my online content"
    weight = 1
    [languages.en.menu]
    [[languages.en.menu.main]]
      name = 'Home'
      url = '/'
      weight = 0
    [[languages.en.menu.main]]
      name = 'Memes'
      url = '/memes'
      weight = 0
