baseURL = "https://marek.omasta.net"
languageCode = "en-gb"
title = "Marek Omasta"
theme = ["blank"]
enableRobotsTXT = true
loadJQuery = false
timeout = "180s"

defaultContentLang = 'en'
[languages]
  [languages.cz]
    contentDir = 'content/cz'
    languageName = 'Čeština'
    weight = 2
    [languages.cz.menu]
    [[languages.cz.menu.main]]
      name = 'Domů'
      url = '/cz/'
      weight = 0
    [[languages.cz.menu.main]]
      name = 'Memes'
      url = '/memes'
      weight = 0
  [languages.en]
    contentDir = 'content/en'
    languageName = 'English'
    weight = 1
    [languages.en.menu]
    [[languages.en.menu.main]]
      name = 'Home'
      url = '/'
      weight = 0
    [[languages.en.menu.main]]
      name = 'Memes'
      url = '/memes'
      weight = 0
