baseURL: https://marek.omasta.net/
title: Marek Omasta
theme:
  - blank
defaultContentLanguage: en
enableRobotsTXT: true
loadJQuery: false
printI18nWarnings: true
removePathAccents: true
timeout: 180s
titleCaseStyle: none

minify:
  minifyOutput: true
  tdewolff:
    html:
      KeepSpecialComments: true
      keepComments: false
      keepQuotes: true
      keepWhitespace: false
    xml:
      keepWhitespace: false

markup:
  goldmark:
    renderer:
      unsafe: true
    extensions:
      typographer:
          disable: true

params:
  dateFormatISO: 2006-01-02T15:04:05
  icons:
    favicon: "/favicon.ico"
    favicon_32: "/images/favicon-32.png"
    favicon_192: "/images/favicon-192.png"
    apple_touch: "/images/favicon-180.png"
  images:
    - images/profile-picture-og.jpg
  author:
    name: Marek Omasta
    email: marek@omasta.net
    image: images/profile-picture@2x.webp
    profiles:
      - Bandcamp: "https://bandcamp.com/m_omasta"
      - ČSFD: "https://csfd.cz/uzivatel/827068-m-omasta/"
      - Discord: "https://discordapp.com/users/m.omasta"
      - Geocaching: "https://geocaching.com/p/?id=8404971"
      - GitHub: "https://github.com/momasta"
      - Goodreads: "https://goodreads.com/m_omasta"
      - Gravatar: "https://gravatar.com/omastik"
      - Last.fm: "https://last.fm/user/m_omasta"
      - Messenger: "https://m.me/omastik"
      - Mastodon: "https://mastodon.social/@marek_omasta"
      - Apple Music: "https://music.apple.com/profile/m_omasta"
      - Pinterest: "https://pinterest.com/m_omasta"
      - Reddit: "https://reddit.com/user/m_omasta"
      - Unsplash: "https://unsplash.com/@m_omasta"
      - YouTube: "https://youtube.com/@m.omasta"
          
taxonomies:
  tag: tags

outputs:
  home:
    - html
  section:
    - html
  taxonomy:
    - html
  term:
    - html

languages:
  en:
    contentDir: content/en
    languageName: English
    languageCode: en-GB
    weight: 1
    params:
      dateFormat: 2 Jan 2006
      description: Personal website of Marek Omasta – blog posts, meme collection, links to my
        profiles and my content online.
    menu:
      main:
        - name: Home
          pageref: /
          weight: 1
        - name: Memes
          pageref: /memes
          weight: 2
  
  cs:
    contentDir: content/cs
    languageName: Čeština
    languageCode: cs-CZ
    weight: 2
    params:
      dateFormat: 2. 1. 2006
      description:
        Osobní web Marka Omasty – články, sbírka memes, odkazy na moje profily a
        obsah na internetu.
    menu:
      main:
        - name: Domů
          pageref: /
          weight: 1
        - name: Memes
          pageref: /memes
          weight: 2
