baseURL = "https://marek.omasta.net"
title = "Marek Omasta"
theme = ["blank"]
enableRobotsTXT = true
loadJQuery = false
timeout = "180s"
summaryLength = 18

defaultContentLanguage = 'en'

[languages]
  [languages.cs]
    contentDir = 'content/cz'
    languageName = 'Čeština'
    languageCode = "cs"
    weight = 2
    [languages.cs.menu]
    [[languages.cs.menu.main]]
      name = 'Domů'
      url = '/cz/'
      weight = 0
    [[languages.cs.menu.main]]
      name = 'Memes'
      url = '/memes'
      weight = 0
  [languages.en]
    contentDir = 'content/en'
    languageName = 'English'
    languageCode = "en-gb"
    weight = 1
    [languages.en.menu]
    [[languages.en.menu.main]]
      name = 'Home'
      url = '/'
      weight = 0
    [[languages.en.menu.main]]
      name = 'Memes'
      url = '/memes'
      weight = 0
